import sqlite3
c=sqlite3.connect('hydra.db'); q=lambda s:c.execute(s).fetchall()
for t in ['charts','songmeta','results','paths','path_refs','dynamics','meta']: print(t,q(f'select count(*) from {t}'))
print('meta',q('select * from meta'))
print('charts distinct md5',q('select count(distinct md5) from charts'))
print('results by version/mode/ms_enabled',q('select hyversion,chartmode,ms_enabled,count(*) from results group by 1,2,3 order by 4 desc'))
print('results per chart+mode dist',q('select n,count(*) from (select count(*) n from results group by hyhash,chartmode) group by n'))
print('results settings combos',q('select sp_cap,ms_enabled,ms_value,depth_mode,depth_value,legacy_fills,count(*) from results group by 1,2,3,4,5,6 order by 7 desc limit 15'))
print('results whose chart is not in charts',q('select count(*) from results where hyhash not in (select md5 from charts)'))
print('songmeta not in charts',q('select count(*) from songmeta where hyhash not in (select md5 from charts)'))
print('songmeta without results',q('select count(*) from songmeta where hyhash not in (select hyhash from results)'))
print('paths unreferenced',q('select count(*), sum(length(payload)) from paths p where not exists (select 1 from path_refs r where r.hyhash=p.hyhash and r.chartmode=p.chartmode and r.phash=p.phash)'))
print('refs per path dist',q('select n,count(*) from (select count(*) n from path_refs group by hyhash,chartmode,phash) group by n order by n limit 12'))
print('paths per result',q('select min(n),avg(n),max(n) from (select count(*) n from path_refs group by result_id)'))
print('paths per chart+mode',q('select min(n),avg(n),max(n) from (select count(*) n from paths group by hyhash,chartmode)'))
for col,t in [('payload','paths'),('structure','results'),('bestpath','results'),('tempomap','songmeta'),('blob','dynamics'),('path','charts'),('folder','charts'),('sig','charts'),('name','charts')]:
  print(t,col,q(f'select sum(length({col})),avg(length({col})),max(length({col})) from {t}'))
print('payload size pct',[q(f"select length(payload) from paths order by length(payload) limit 1 offset (select count(*)*{p}/100 from paths)") for p in (10,50,90,99)])
print('tempomap size pct',[q(f"select length(tempomap) from songmeta order by length(tempomap) limit 1 offset (select count(*)*{p}/100 from songmeta)") for p in (10,50,90,99)])
print('top payload per chart',q('select hyhash,chartmode,count(*),sum(length(payload)) s from paths group by 1,2 order by s desc limit 8'))
print('charts dup md5',q('select count(*) from (select md5 from charts group by md5 having count(*)>1)'))
