// Tests for app/analysis.{h,cpp}: discovery/hashing sanity over the real
// testdata/input corpus.

#include "doctest.h"

#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <map>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <utility>
#include <vector>

#include "app/analysis.h"
#include "app/work_pool.h"
#include "core/winstr.h"
#include "corpus_util.h"
#include "midi_util.h"
#include "parse/song.h"
#include "sng_util.h"
#include "store/record_store.h"

#ifndef HYDRA_TESTDATA_DIR
#error "HYDRA_TESTDATA_DIR must be defined (see CMakeLists.txt)"
#endif

using namespace hydra::app;

using hydra::file_exists_utf8;

TEST_CASE("discover_charts walks the corpus without throwing") {
    auto [items, errors] = discover_charts({std::string(HYDRA_INPUT_DIR)});
    CHECK(errors.empty());

    for (const ScanItem& item : items) {
        CHECK_MESSAGE(file_exists_utf8(item.notespath), item.notespath);
        CHECK(item.md5.size() == 32);
        for (char c : item.md5)
            CHECK((std::isxdigit(static_cast<unsigned char>(c)) != 0));
    }

    MESSAGE("discovered " << items.size() << " chart(s)");
}

TEST_CASE("discover_charts returns nothing for an empty root list") {
    auto [items, errors] = discover_charts({});
    CHECK(items.empty());
    CHECK(errors.empty());
}

namespace {

// notespath/rootfolder relative to testdata/input, forward slashes — the
// keying testdata/scan_snapshot.json uses (see tools/bench.cpp's --dump-rel).
std::string rel_of(const std::string& path, const std::string& root) {
    std::string rel = path;
    if (!root.empty() && rel.size() > root.size() && rel.compare(0, root.size(), root) == 0)
        rel = rel.substr(root.size() + 1);
    for (char& c : rel)
        if (c == '\\') c = '/';
    return rel;
}

}  // namespace

// The fixture was generated by the pre-rework serial scanner (whole-file MD5,
// separate metadata reads), so this pins the digests, metadata, and discovery
// set across any scan implementation change.
TEST_CASE("discover_charts output matches the checked-in scan snapshot") {
    const std::string input = HYDRA_INPUT_DIR;
    std::ifstream f(std::string(HYDRA_TESTDATA_DIR) + "/scan_snapshot.json",
                    std::ios::binary);
    REQUIRE_MESSAGE(bool(f), "missing testdata/scan_snapshot.json");
    std::stringstream ss;
    ss << f.rdbuf();
    corpus::json snapshot = corpus::json::parse(ss.str());

    auto [items, errors] = discover_charts({input});
    CHECK(errors.empty());
    CHECK(items.size() == snapshot.size());

    std::map<std::string, const ScanItem*> by_rel;
    for (const ScanItem& item : items) by_rel[rel_of(item.notespath, input)] = &item;

    for (const auto& row : snapshot) {
        const std::string rel = row["path"].get<std::string>();
        auto it = by_rel.find(rel);
        REQUIRE_MESSAGE(it != by_rel.end(), "not discovered: " << rel);
        const ScanItem& item = *it->second;
        CHECK_MESSAGE(item.md5 == row["md5"].get<std::string>(), rel);
        CHECK_MESSAGE(item.title == row["title"].get<std::string>(), rel);
        CHECK_MESSAGE(item.artist == row["artist"].get<std::string>(), rel);
        CHECK_MESSAGE(item.charter == row["charter"].get<std::string>(), rel);
        CHECK_MESSAGE(rel_of(item.rootfolder, "") == row["folder"].get<std::string>(), rel);
    }
}

TEST_CASE("rescan cache reproduces the scan without reading chart files") {
    const std::string input = HYDRA_INPUT_DIR;
    auto [items, errors] = discover_charts({input});
    REQUIRE(errors.empty());
    REQUIRE(!items.empty());

    hydra::store::RecordStore store(":memory:");
    std::vector<hydra::store::ChartLibraryEntry> entries;
    for (const ScanItem& it : items) entries.push_back(to_library_entry(it));
    store.rebuild_chart_library(entries);

    hydra::store::ChartLibraryCache cache = store.chart_library_cache();
    CHECK(cache.size() == items.size());

    int last_cached = 0, last_done = 0;
    ScanCallbacks callbacks;
    callbacks.on_charts = [&](int done, int, int cached) {
        last_done = done;
        last_cached = cached;
    };
    auto [items2, errors2] = discover_charts({input}, callbacks, &cache);
    CHECK(errors2.empty());

    // Every chart came out of the cache (no file was opened for content)...
    CHECK(last_done == static_cast<int>(items.size()));
    CHECK(last_cached == static_cast<int>(items.size()));

    // ...and the results are identical, field for field, in the same order.
    REQUIRE(items2.size() == items.size());
    for (size_t i = 0; i < items.size(); ++i) {
        CHECK(items2[i].md5 == items[i].md5);
        CHECK(items2[i].title == items[i].title);
        CHECK(items2[i].artist == items[i].artist);
        CHECK(items2[i].charter == items[i].charter);
        CHECK(items2[i].notespath == items[i].notespath);
        CHECK(items2[i].rootfolder == items[i].rootfolder);
        CHECK(items2[i].sig == items[i].sig);
    }
}

TEST_CASE("run_batch files results under the lens it is given") {
    const std::string chart = corpus::first_chart_with_notes();

    BatchRun run;
    run.chartmode = "lens-test";
    run.lens = hydra::store::Lens::from(std::optional<int>(10), 0, 10);
    run.settings.depth_mode = hydra::DepthMode::Scores;
    run.settings.depth_value = 10;
    run.settings.ms_filter = 10.0;

    ScanItem item;
    item.md5 = hash_chart_file(chart);
    item.title = "t";
    item.notespath = chart;
    hydra::store::RecordStore store(":memory:");
    run_batch({item}, run, store, /*redo=*/false, 1);

    const hydra::store::CapQuery cap =
        hydra::store::CapQuery::at(run.settings.sp_cap);
    CHECK(store.has_record(hydra::store::RecordKey{item.md5, "lens-test", cap, run.lens}));
}

TEST_CASE("run_work_pool hands every item to the consumer once") {
    std::vector<int> seen(100, 0);
    run_work_pool<size_t>(
        100, 8, nullptr, [](size_t i) { return i; }, [&](size_t&& i) { ++seen[i]; });
    for (int n : seen) CHECK(n == 1);
}

TEST_CASE("run_work_pool: a cancel mid-run never strands the consumer") {
    // Hundreds of short runs, each cancelled from inside the work. The old
    // batch pool could leave its consumer waiting forever when every worker
    // saw the cancel between items, so a hang is the failure this guards. The
    // watchdog turns a hang into a failed check instead of a stuck suite.
    //
    // The watchdog judges progress, not total time. A hang stops the rounds
    // for good; a busy machine only slows them (on a loaded CPU, 500 rounds
    // of 8 fresh threads can take well over 30 s). So it fails only when no
    // round has finished for 30 s. The counter is shared, because a failed
    // check leaves the test while the detached thread may still run.
    auto rounds_done = std::make_shared<std::atomic<int>>(0);
    std::promise<bool> finished;
    std::future<bool> outcome = finished.get_future();
    std::thread([p = std::move(finished), rounds_done]() mutable {
        bool every_item_consumed = true;
        for (int round = 0; round < 500; ++round) {
            std::atomic<bool> cancel{false};
            std::atomic<int> worked{0};
            int consumed = 0;
            run_work_pool<int>(
                64, 8, &cancel,
                [&](size_t i) {
                    ++worked;
                    if (i == 3) cancel = true;
                    return static_cast<int>(i);
                },
                [&](int&&) { ++consumed; });
            // Every item a worker started reached the consumer.
            if (consumed != worked.load()) every_item_consumed = false;
            ++*rounds_done;
        }
        p.set_value(every_item_consumed);
    }).detach();

    const auto t0 = std::chrono::steady_clock::now();
    int last = 0;
    while (outcome.wait_for(std::chrono::seconds(30)) != std::future_status::ready) {
        const int now = rounds_done->load();
        REQUIRE_MESSAGE(now != last, "run_work_pool never returned: its consumer was left waiting"
                                     " (no round finished in 30 s; stuck in round "
                                         << now << ")");
        last = now;
    }
    MESSAGE("500 rounds took "
            << std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count()
            << " s");
    CHECK(outcome.get());
}

// R7.22: batch_worker_count owns the floor of 1. The pool checks the count it
// is given instead of quietly raising it: with no workers nothing would ever
// reach the consumer.
TEST_CASE("run_work_pool refuses a worker count below 1") {
    int consumed = 0;
    CHECK_THROWS_AS(run_work_pool<size_t>(
                        100, 0, nullptr, [](size_t i) { return i; },
                        [&](size_t&&) { ++consumed; }),
                    std::invalid_argument);
    CHECK(consumed == 0);
    CHECK(batch_worker_count() >= 1);
}

// Audit finding 256: the scan row and the library entry hold the same seven
// strings; the conversion copies each one by name.
TEST_CASE("to_library_entry copies every ScanItem field by name") {
    ScanItem item;
    item.md5 = "the md5";
    item.title = "the title";
    item.artist = "the artist";
    item.charter = "the charter";
    item.notespath = "the notespath";
    item.rootfolder = "the rootfolder";
    item.sig = "the sig";

    const hydra::store::ChartLibraryEntry e = to_library_entry(item);
    CHECK(e.md5 == "the md5");
    CHECK(e.title == "the title");
    CHECK(e.artist == "the artist");
    CHECK(e.charter == "the charter");
    CHECK(e.notespath == "the notespath");
    CHECK(e.rootfolder == "the rootfolder");
    CHECK(e.sig == "the sig");
}

// Audit finding 192: one spelling of a chart hash for matching.
TEST_CASE("normalize_chart_hash lowers a hash and leaves a lowercase one alone") {
    CHECK(normalize_chart_hash("0123456789ABCDEFabcdef0123456789") ==
          "0123456789abcdefabcdef0123456789");
    CHECK(normalize_chart_hash("0123456789abcdefabcdef0123456789") ==
          "0123456789abcdefabcdef0123456789");
    // The scan's own hash is already in that spelling.
    const std::string md5 = hash_chart_file(corpus::first_chart_with_notes());
    REQUIRE(!md5.empty());
    CHECK(normalize_chart_hash(md5) == md5);
}

namespace {

// Items for a fake analyzer: nothing is read from disk.
std::vector<ScanItem> fake_items(int n) {
    std::vector<ScanItem> items;
    for (int i = 0; i < n; ++i) {
        ScanItem item;
        item.md5 = "fake" + std::to_string(i);
        item.title = "fake " + std::to_string(i);
        item.notespath = "fake_" + std::to_string(i) + ".chart";
        items.push_back(item);
    }
    return items;
}

}  // namespace

TEST_CASE("run_batch: cancel stops running searches within seconds") {
    // A stand-in for a heavy chart: it runs for 10 s, reporting progress every
    // millisecond the way the engine's sweep does. Only a progress callback
    // that throws on cancel can stop it early. 10 s is twice the 5 s pass
    // line, so a broken cancel still fails, in about 40 s rather than minutes.
    std::atomic<int> started{0};
    BatchCallbacks callbacks;
    callbacks.analyze = [&started](const std::string&, const AnalysisSettings&,
                                   const std::function<void(float)>& on_progress)
        -> AnalysisResult {
        ++started;
        const auto until = std::chrono::steady_clock::now() + std::chrono::seconds(10);
        while (std::chrono::steady_clock::now() < until) {
            if (on_progress) on_progress(0.5f);
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
        throw std::runtime_error("the fake search ran its full 10 s");
    };
    std::atomic<bool> cancel{false};
    callbacks.cancel = &cancel;
    int errors = 0, results = 0;
    callbacks.on_error = [&errors](const std::string&, const std::string&) { ++errors; };
    callbacks.on_result = [&results](const ScanItem&, const hydra::store::PreparedRow&) {
        ++results;
    };

    // Press cancel once all four workers are inside a search.
    std::thread canceller([&] {
        const auto give_up = std::chrono::steady_clock::now() + std::chrono::seconds(10);
        while (started.load() < 4 && std::chrono::steady_clock::now() < give_up)
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        cancel = true;
    });

    hydra::store::RecordStore store(":memory:");
    BatchRun run;
    run.chartmode = "cancel-test";
    const auto t0 = std::chrono::steady_clock::now();
    run_batch(fake_items(16), run, store, /*redo=*/false, /*worker_count=*/4, callbacks);
    const double seconds =
        std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    canceller.join();

    CHECK(started.load() == 4);  // no chart started after the cancel
    CHECK(seconds < 5.0);        // without the cancel check this takes 40 s
    CHECK(errors == 0);          // a stopped search is not a failure...
    CHECK(results == 0);         // ...and not a result
    CHECK(store.counts().second == 0);
}

TEST_CASE("run_batch: a cancelled real search is neither a result nor a failure") {
    const std::string chart = corpus::first_chart_with_notes();

    ScanItem item;
    item.md5 = hash_chart_file(chart);
    item.title = "t";
    item.notespath = chart;

    std::atomic<bool> cancel{false};
    BatchCallbacks callbacks;
    callbacks.cancel = &cancel;
    // The real analysis, with cancel pressed at the search's first progress
    // tick. The throw has to unwind the engine, the pather and the all-0 pass
    // without any of them catching it.
    callbacks.analyze = [&cancel](const std::string& path, const AnalysisSettings& s,
                                  const std::function<void(float)>& on_progress) {
        return analyze_chart_file(path, s, [&](float f) {
            cancel = true;
            on_progress(f);
        });
    };
    int errors = 0, results = 0;
    callbacks.on_error = [&errors](const std::string&, const std::string&) { ++errors; };
    callbacks.on_result = [&results](const ScanItem&, const hydra::store::PreparedRow&) {
        ++results;
    };

    hydra::store::RecordStore store(":memory:");
    BatchRun run;
    run.chartmode = "cancel-test";
    run_batch({item}, run, store, /*redo=*/false, 1, callbacks);

    CHECK(errors == 0);
    CHECK(results == 0);
    CHECK(store.counts().second == 0);
}

TEST_CASE("run_batch analyzes a chart found in two folders once") {
    // D51 call 10 (finding 63): two copies of one chart are one chart. The
    // batch used to analyze it once per folder and count each copy.
    const std::string chart = corpus::first_chart_with_notes();
    ScanItem first;
    first.md5 = hash_chart_file(chart);
    first.title = "t";
    first.notespath = chart;
    ScanItem second = first;
    second.notespath = "C:\\charts\\copy\\notes.chart";

    // Both copies hold the same bytes, so the analyzer reads the one real
    // file whichever copy it is handed, and counts each run.
    std::atomic<int> runs{0};
    std::atomic<int> total{-1};
    BatchCallbacks callbacks;
    callbacks.analyze = [&](const std::string&, const AnalysisSettings& s,
                            const std::function<void(float)>& on_progress) {
        ++runs;
        return analyze_chart_file(chart, s, on_progress);
    };
    callbacks.on_progress = [&total](const BatchProgress& p) { total = p.total; };

    BatchRun run;
    run.chartmode = "dedupe-test";
    run.lens = hydra::store::Lens::from(std::optional<int>(10), 0, 10);
    run.settings.depth_mode = hydra::DepthMode::Scores;
    run.settings.depth_value = 10;
    run.settings.ms_filter = 10.0;
    hydra::store::RecordStore store(":memory:");
    run_batch({first, second}, run, store, /*redo=*/false, 1, callbacks);

    CHECK(total.load() == 1);
    CHECK(runs.load() == 1);
}

TEST_CASE("discover_charts: a song with no usable name reads (unknown)") {
    namespace fs = std::filesystem;
    const std::string chart = corpus::first_chart_with_suffix(".chart");
    REQUIRE(!chart.empty());

    const fs::path root = fs::temp_directory_path() /
        ("hydra_unknown_title_" + std::to_string(GetCurrentProcessId()));
    fs::remove_all(root);

    // An empty `name =` line.
    fs::create_directories(root / "empty_name");
    fs::copy_file(fs::u8path(chart), root / "empty_name" / "notes.chart");
    {
        std::ofstream ini(root / "empty_name" / "song.ini", std::ios::binary);
        ini << "[song]\nname =\nartist = Someone\n";
    }
    // No name line at all.
    fs::create_directories(root / "no_name");
    fs::copy_file(fs::u8path(chart), root / "no_name" / "notes.chart");
    {
        std::ofstream ini(root / "no_name" / "song.ini", std::ios::binary);
        ini << "[song]\nartist = Someone\n";
    }
    // A .sng whose embedded name is empty.
    {
        const std::vector<uint8_t> sng =
            testsng::make_sng({{"name", ""}, {"artist", "Someone"}, {"charter", "C"}}, {});
        std::ofstream f(root / "blank.sng", std::ios::binary);
        f.write(reinterpret_cast<const char*>(sng.data()),
                static_cast<std::streamsize>(sng.size()));
    }

    auto [items, errors] = discover_charts({root.u8string()});
    fs::remove_all(root);
    CHECK(errors.empty());
    REQUIRE(items.size() == 3);
    for (const ScanItem& it : items) {
        CAPTURE(it.notespath);
        CHECK(it.title == hydra::kUnknownTitle);
        CHECK(it.artist == "Someone");
    }
}

TEST_CASE("rescan cache: an old placeholder or blank title reads (unknown)") {
    const std::string input = HYDRA_INPUT_DIR;
    auto [items, errors] = discover_charts({input});
    REQUIRE(!items.empty());

    // Library rows written before the fallback existed: a blank title from an
    // empty `name =`, or the old readers' "<unknown title>".
    hydra::store::RecordStore store(":memory:");
    std::vector<hydra::store::ChartLibraryEntry> entries;
    for (size_t i = 0; i < items.size(); ++i) {
        hydra::store::ChartLibraryEntry e = to_library_entry(items[i]);
        e.title = i % 2 ? "<unknown title>" : "";
        entries.push_back(std::move(e));
    }
    store.rebuild_chart_library(entries);
    hydra::store::ChartLibraryCache cache = store.chart_library_cache();

    auto [items2, errors2] = discover_charts({input}, ScanCallbacks{}, &cache);
    REQUIRE(items2.size() == items.size());
    for (const ScanItem& it : items2) CHECK(it.title == hydra::kUnknownTitle);
}

namespace {

// A fresh folder under %TEMP% for one scan fixture.
std::string scan_fixture_dir(const char* name) {
    wchar_t tmp[MAX_PATH];
    GetTempPathW(MAX_PATH, tmp);
    std::string dir = hydra::wide_to_utf8(tmp) + "hydra_scan_case_" +
                      std::to_string(GetCurrentProcessId()) + "_" + name;
    CreateDirectoryW(hydra::utf8_to_wide(dir).c_str(), nullptr);
    return dir;
}

void write_fixture(const std::string& path, const std::vector<uint8_t>& bytes) {
    FILE* f = hydra::fopen_utf8(path, L"wb");
    REQUIRE_MESSAGE(f != nullptr, "cannot write " << path);
    if (!bytes.empty()) std::fwrite(bytes.data(), 1, bytes.size(), f);
    std::fclose(f);
}

}  // namespace

TEST_CASE("discover_charts finds a folder whose notes and ini names are capitalized") {
    const std::string dir = scan_fixture_dir("caps");
    write_fixture(dir + "\\Notes.mid",
                  testmidi::smf(testmidi::concat({testmidi::track_name("PART DRUMS"),
                                                  testmidi::set_tempo(),
                                                  testmidi::note_on(96, 100),
                                                  testmidi::end_of_track()})));
    const std::string ini = "[song]\r\nname = Capital Case\r\nartist = Someone\r\n"
                            "charter = Someone Else\r\n";
    write_fixture(dir + "\\Song.ini", std::vector<uint8_t>(ini.begin(), ini.end()));

    auto [items, errors] = discover_charts({dir});
    REQUIRE(errors.empty());
    REQUIRE(items.size() == 1);
    CHECK(items[0].title == "Capital Case");
    CHECK(items[0].notespath == dir + "\\Notes.mid");
}
