// Tests for app/analysis.{h,cpp}: discovery/hashing sanity over the real
// testdata/input corpus.

#include "doctest.h"

#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>

#include <algorithm>
#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <functional>
#include <future>
#include <map>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <thread>
#include <utility>
#include <unordered_set>
#include <vector>

#include <sqlite3.h>

#include "app/analysis.h"
#include "app/work_pool.h"
#include "core/error_kind.h"
#include "audio_chart_fixtures.h"
#include "core/strutil.h"
#include "core/winstr.h"
#include "corpus_util.h"
#include "midi_util.h"
#include "parse/song.h"
#include "sng_util.h"
#include "store/record_store.h"
#include "temp_util.h"

#ifndef HYDRA_TESTDATA_DIR
#error "HYDRA_TESTDATA_DIR must be defined (see CMakeLists.txt)"
#endif

using namespace hydra::app;

using hydra::file_exists_utf8;

TEST_CASE("discover_charts walks the corpus without throwing") {
    auto [items, errors] = discover_charts({std::string(HYDRA_INPUT_DIR)});
    CHECK(errors.empty());

    for (const ScanItem& item : items) {
        CHECK_MESSAGE(file_exists_utf8(item.notespath), item.notespath);
        CHECK(item.md5.size() == 32);
        for (char c : item.md5)
            CHECK((std::isxdigit(static_cast<unsigned char>(c)) != 0));
    }

    MESSAGE("discovered " << items.size() << " chart(s)");
}

TEST_CASE("discover_charts returns nothing for an empty root list") {
    auto [items, errors] = discover_charts({});
    CHECK(items.empty());
    CHECK(errors.empty());
}

namespace {

// A scan row for one real chart file, for the run_batch cases that analyze it.
ScanItem chart_item(const std::string& chart) {
    ScanItem item;
    item.md5 = hash_chart_file(chart);
    item.title = "t";
    item.notespath = chart;
    return item;
}

}  // namespace

// The fixture was generated by the pre-rework serial scanner (whole-file MD5,
// separate metadata reads), so this pins the digests, metadata, and discovery
// set across any scan implementation change.
TEST_CASE("discover_charts output matches the checked-in scan snapshot") {
    const std::string input = HYDRA_INPUT_DIR;
    std::ifstream f(std::string(HYDRA_TESTDATA_DIR) + "/scan_snapshot.json",
                    std::ios::binary);
    REQUIRE_MESSAGE(bool(f), "missing testdata/scan_snapshot.json");
    std::stringstream ss;
    ss << f.rdbuf();
    corpus::json snapshot = corpus::json::parse(ss.str());

    auto [items, errors] = discover_charts({input});
    CHECK(errors.empty());
    CHECK(items.size() == snapshot.size());

    std::map<std::string, const ScanItem*> by_rel;
    // Keyed as the snapshot keys it (hydra::relative_slash_path owns the rule).
    for (const ScanItem& item : items)
        by_rel[hydra::relative_slash_path(item.notespath, input)] = &item;

    for (const auto& row : snapshot) {
        const std::string rel = row["path"].get<std::string>();
        auto it = by_rel.find(rel);
        REQUIRE_MESSAGE(it != by_rel.end(), "not discovered: " << rel);
        const ScanItem& item = *it->second;
        CHECK_MESSAGE(item.md5 == row["md5"].get<std::string>(), rel);
        CHECK_MESSAGE(item.title == row["title"].get<std::string>(), rel);
        CHECK_MESSAGE(item.artist == row["artist"].get<std::string>(), rel);
        CHECK_MESSAGE(item.charter == row["charter"].get<std::string>(), rel);
        CHECK_MESSAGE(hydra::relative_slash_path(item.rootfolder, "") ==
                          row["folder"].get<std::string>(),
                      rel);
    }
}

TEST_CASE("rescan cache reproduces the scan without reading chart files") {
    const std::string input = HYDRA_INPUT_DIR;
    auto [items, errors] = discover_charts({input});
    REQUIRE(errors.empty());
    REQUIRE(!items.empty());

    hydra::store::RecordStore store(":memory:");
    std::vector<hydra::store::ChartLibraryEntry> entries;
    for (const ScanItem& it : items) entries.push_back(to_library_entry(it));
    store.rebuild_chart_library(entries);

    hydra::store::ChartLibraryCache cache = store.chart_library_cache();
    CHECK(cache.size() == items.size());

    int last_cached = 0, last_done = 0;
    ScanCallbacks callbacks;
    callbacks.on_charts = [&](int done, int, int cached) {
        last_done = done;
        last_cached = cached;
    };
    auto [items2, errors2] = discover_charts({input}, callbacks, &cache);
    CHECK(errors2.empty());

    // Every chart came out of the cache (no file was opened for content)...
    CHECK(last_done == static_cast<int>(items.size()));
    CHECK(last_cached == static_cast<int>(items.size()));

    // ...and the results are identical, field for field, in the same order.
    REQUIRE(items2.size() == items.size());
    for (size_t i = 0; i < items.size(); ++i) {
        CHECK(items2[i].md5 == items[i].md5);
        CHECK(items2[i].title == items[i].title);
        CHECK(items2[i].artist == items[i].artist);
        CHECK(items2[i].charter == items[i].charter);
        CHECK(items2[i].notespath == items[i].notespath);
        CHECK(items2[i].rootfolder == items[i].rootfolder);
        CHECK(items2[i].sig == items[i].sig);
    }
}

TEST_CASE("run_batch files results under the lens it is given") {
    const std::string chart = corpus::first_chart_with_notes();

    BatchRun run;
    run.chartmode = "lens-test";
    run.lens = hydra::store::Lens::from(std::optional<int>(10), 0, 10);
    run.settings.depth_mode = hydra::DepthMode::Scores;
    run.settings.depth_value = 10;
    run.settings.ms_filter = 10.0;

    const ScanItem item = chart_item(chart);
    hydra::store::RecordStore store(":memory:");
    run_batch({item}, run, store, /*redo=*/false, 1);

    const hydra::store::CapQuery cap =
        hydra::store::CapQuery::at(run.settings.sp_cap);
    CHECK(store.has_record(hydra::store::RecordKey{item.md5, "lens-test", cap, run.lens}));
}

TEST_CASE("run_work_pool hands every item to the consumer once") {
    std::vector<int> seen(100, 0);
    run_work_pool<size_t>(
        100, 8, nullptr, [](size_t i) { return i; }, [&](size_t&& i) { ++seen[i]; });
    for (int n : seen) CHECK(n == 1);
}

TEST_CASE("run_work_pool: a cancel mid-run never strands the consumer") {
    // Hundreds of short runs, each cancelled from inside the work. The old
    // batch pool could leave its consumer waiting forever when every worker
    // saw the cancel between items, so a hang is the failure this guards. The
    // watchdog turns a hang into a failed check instead of a stuck suite.
    //
    // The watchdog judges progress, not total time. A hang stops the rounds
    // for good; a busy machine only slows them (on a loaded CPU, 500 rounds
    // of 8 fresh threads can take well over 30 s). So it fails only when no
    // round has finished for 30 s. The counter is shared, because a failed
    // check leaves the test while the detached thread may still run.
    auto rounds_done = std::make_shared<std::atomic<int>>(0);
    std::promise<bool> finished;
    std::future<bool> outcome = finished.get_future();
    std::thread([p = std::move(finished), rounds_done]() mutable {
        bool every_item_consumed = true;
        for (int round = 0; round < 500; ++round) {
            std::atomic<bool> cancel{false};
            std::atomic<int> worked{0};
            int consumed = 0;
            run_work_pool<int>(
                64, 8, &cancel,
                [&](size_t i) {
                    ++worked;
                    if (i == 3) cancel = true;
                    return static_cast<int>(i);
                },
                [&](int&&) { ++consumed; });
            // Every item a worker started reached the consumer.
            if (consumed != worked.load()) every_item_consumed = false;
            ++*rounds_done;
        }
        p.set_value(every_item_consumed);
    }).detach();

    const auto t0 = std::chrono::steady_clock::now();
    int last = 0;
    while (outcome.wait_for(std::chrono::seconds(30)) != std::future_status::ready) {
        const int now = rounds_done->load();
        REQUIRE_MESSAGE(now != last, "run_work_pool never returned: its consumer was left waiting"
                                     " (no round finished in 30 s; stuck in round "
                                         << now << ")");
        last = now;
    }
    MESSAGE("500 rounds took "
            << std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count()
            << " s");
    CHECK(outcome.get());
}

// R7.22: batch_worker_count owns the floor of 1. The pool checks the count it
// is given instead of quietly raising it: with no workers nothing would ever
// reach the consumer.
TEST_CASE("run_work_pool refuses a worker count below 1") {
    int consumed = 0;
    CHECK_THROWS_AS(run_work_pool<size_t>(
                        100, 0, nullptr, [](size_t i) { return i; },
                        [&](size_t&&) { ++consumed; }),
                    std::invalid_argument);
    CHECK(consumed == 0);
    CHECK(batch_worker_count() >= 1);
}

// Audit finding 256: the scan row and the library entry hold the same seven
// strings; the conversion copies each one by name.
TEST_CASE("to_library_entry copies every ScanItem field by name") {
    ScanItem item;
    item.md5 = "the md5";
    item.title = "the title";
    item.artist = "the artist";
    item.charter = "the charter";
    item.notespath = "the notespath";
    item.rootfolder = "the rootfolder";
    item.sig = "the sig";

    const hydra::store::ChartLibraryEntry e = to_library_entry(item);
    CHECK(e.md5 == "the md5");
    CHECK(e.title == "the title");
    CHECK(e.artist == "the artist");
    CHECK(e.charter == "the charter");
    CHECK(e.notespath == "the notespath");
    CHECK(e.rootfolder == "the rootfolder");
    CHECK(e.sig == "the sig");
}

// Audit finding 192: one spelling of a chart hash for matching.
TEST_CASE("normalize_chart_hash lowers a hash and leaves a lowercase one alone") {
    CHECK(normalize_chart_hash("0123456789ABCDEFabcdef0123456789") ==
          "0123456789abcdefabcdef0123456789");
    CHECK(normalize_chart_hash("0123456789abcdefabcdef0123456789") ==
          "0123456789abcdefabcdef0123456789");
    // The scan's own hash is already in that spelling.
    const std::string md5 = hash_chart_file(corpus::first_chart_with_notes());
    REQUIRE(!md5.empty());
    CHECK(normalize_chart_hash(md5) == md5);
}

namespace {

// Items for a fake analyzer: nothing is read from disk.
std::vector<ScanItem> fake_items(int n) {
    std::vector<ScanItem> items;
    for (int i = 0; i < n; ++i) {
        ScanItem item;
        item.md5 = "fake" + std::to_string(i);
        item.title = "fake " + std::to_string(i);
        item.notespath = "fake_" + std::to_string(i) + ".chart";
        item.timing = hydra::store::ChartTimingMeta{};  // states nothing, so no file is read
        items.push_back(item);
    }
    return items;
}

}  // namespace

TEST_CASE("run_batch: cancel stops running searches within seconds") {
    // A stand-in for a heavy chart: it runs for 10 s, reporting progress every
    // millisecond the way the engine's sweep does. Only a progress callback
    // that throws on cancel can stop it early. 10 s is twice the 5 s pass
    // line, so a broken cancel still fails, in about 40 s rather than minutes.
    std::atomic<int> started{0};
    BatchCallbacks callbacks;
    callbacks.analyze = [&started](const std::string&, const AnalysisSettings&,
                                   const std::function<void(float)>& on_progress)
        -> AnalysisResult {
        ++started;
        const auto until = std::chrono::steady_clock::now() + std::chrono::seconds(10);
        while (std::chrono::steady_clock::now() < until) {
            if (on_progress) on_progress(0.5f);
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
        throw std::runtime_error("the fake search ran its full 10 s");
    };
    std::atomic<bool> cancel{false};
    callbacks.cancel = &cancel;
    int errors = 0, results = 0;
    callbacks.on_error = [&errors](const std::string&, const std::string&, const std::string&) {
        ++errors;
    };
    callbacks.on_result = [&results](const ScanItem&, const hydra::store::PreparedRow&) {
        ++results;
    };

    // Press cancel once all four workers are inside a search.
    std::thread canceller([&] {
        const auto give_up = std::chrono::steady_clock::now() + std::chrono::seconds(10);
        while (started.load() < 4 && std::chrono::steady_clock::now() < give_up)
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        cancel = true;
    });

    hydra::store::RecordStore store(":memory:");
    BatchRun run;
    run.chartmode = "cancel-test";
    const auto t0 = std::chrono::steady_clock::now();
    run_batch(fake_items(16), run, store, /*redo=*/false, /*worker_count=*/4, callbacks);
    const double seconds =
        std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    canceller.join();

    CHECK(started.load() == 4);  // no chart started after the cancel
    CHECK(seconds < 5.0);        // without the cancel check this takes 40 s
    CHECK(errors == 0);          // a stopped search is not a failure...
    CHECK(results == 0);         // ...and not a result
    CHECK(store.counts().second == 0);
}

TEST_CASE("run_batch: a cancelled real search is neither a result nor a failure") {
    const ScanItem item = chart_item(corpus::first_chart_with_notes());

    std::atomic<bool> cancel{false};
    BatchCallbacks callbacks;
    callbacks.cancel = &cancel;
    // The real analysis, with cancel pressed at the search's first progress
    // tick. The throw has to unwind the engine, the pather and the all-0 pass
    // without any of them catching it.
    callbacks.analyze = [&cancel](const std::string& path, const AnalysisSettings& s,
                                  const std::function<void(float)>& on_progress) {
        return analyze_chart_file(path, s, [&](float f) {
            cancel = true;
            on_progress(f);
        });
    };
    int errors = 0, results = 0;
    callbacks.on_error = [&errors](const std::string&, const std::string&, const std::string&) {
        ++errors;
    };
    callbacks.on_result = [&results](const ScanItem&, const hydra::store::PreparedRow&) {
        ++results;
    };

    hydra::store::RecordStore store(":memory:");
    BatchRun run;
    run.chartmode = "cancel-test";
    run_batch({item}, run, store, /*redo=*/false, 1, callbacks);

    CHECK(errors == 0);
    CHECK(results == 0);
    CHECK(store.counts().second == 0);
}

TEST_CASE("run_batch analyzes a chart found in two folders once, and counts both rows") {
    // D51 call 10 (finding 63): two copies of one chart are analyzed once.
    // D76: both rows count, the way the library counts them.
    std::vector<ScanItem> items = fake_items(1);
    items.push_back(items[0]);
    items[1].notespath = "copy_fake_0.chart";

    // The fake analyzer only counts runs; the dedupe happens before it.
    std::atomic<int> runs{0};
    std::atomic<int> total{-1};
    BatchCallbacks callbacks;
    callbacks.analyze = [&runs](const std::string&, const AnalysisSettings&,
                                const std::function<void(float)>&) -> AnalysisResult {
        ++runs;
        throw std::runtime_error("fake analyzer");
    };
    callbacks.on_progress = [&total](const BatchProgress& p) { total = p.total; };

    BatchRun run;
    run.chartmode = "dedupe-test";
    hydra::store::RecordStore store(":memory:");
    run_batch(items, run, store, /*redo=*/false, 1, callbacks);

    CHECK(total.load() == 2);
    CHECK(runs.load() == 1);
}

namespace {

// Four scan rows for the batch-count cases: chart A, chart B, a second copy
// of A in another folder, then chart C.
std::vector<ScanItem> items_with_a_copy() {
    std::vector<ScanItem> items = fake_items(3);
    ScanItem copy = items[0];
    copy.notespath = "copy_fake_0.chart";
    items.insert(items.begin() + 2, copy);
    return items;
}

}  // namespace

TEST_CASE("plan_batch: a second copy runs with its first and counts as a row") {
    // D51 call 10: the copy is not run again. D76: it adds a row to its
    // chart, so the plan's rows add up to the scan's.
    const std::vector<ScanItem> items = items_with_a_copy();
    const BatchPlan plan = plan_batch(items, {"fake2"});

    REQUIRE(plan.todo.size() == 2);
    CHECK(plan.todo[0].md5 == "fake0");
    CHECK(plan.todo[0].notespath == "fake_0.chart");  // the first copy wins
    CHECK(plan.todo[1].md5 == "fake1");
    CHECK(plan.rows == std::vector<int>{2, 1});
    CHECK(plan.skipped == 1);
    CHECK(plan.todo_rows() + plan.skipped == static_cast<int>(items.size()));
}

TEST_CASE("plan_batch: every copy of a stored chart counts as skipped") {
    std::vector<ScanItem> items = items_with_a_copy();
    const BatchPlan plan = plan_batch(items, {"fake0"});

    REQUIRE(plan.todo.size() == 2);
    CHECK(plan.todo[0].md5 == "fake1");
    CHECK(plan.todo[1].md5 == "fake2");
    CHECK(plan.skipped == 2);
    CHECK(plan.todo_rows() + plan.skipped == static_cast<int>(items.size()));
}

TEST_CASE("run_batch reports analyzed, skipped and failed itself") {
    const std::vector<ScanItem> items = items_with_a_copy();

    // Counts its runs; chart B fails and every other chart stores one real
    // chart's result.
    const AnalysisResult real = analyze_chart_file(corpus::first_chart_with_notes(), {});
    std::atomic<int> runs{0};
    BatchCallbacks callbacks;
    callbacks.analyze = [&runs, &real](const std::string& path, const AnalysisSettings&,
                                       const std::function<void(float)>&) -> AnalysisResult {
        ++runs;
        if (path == "fake_1.chart") throw std::runtime_error("fake analyzer");
        return real;
    };

    BatchRun run;
    run.chartmode = "counts-test";
    hydra::store::RecordStore store(":memory:");
    // Chart C is stored before the batch starts.
    run_batch({items[3]}, run, store, /*redo=*/false, 1, callbacks);
    REQUIRE(runs.load() == 1);

    BatchProgress last;
    callbacks.on_progress = [&last](const BatchProgress& p) { last = p; };
    run_batch(items, run, store, /*redo=*/false, 1, callbacks);

    // Chart A runs once for both its rows (D51 call 10), and both count (D76).
    CHECK(runs.load() == 3);
    CHECK(last.total == 3);
    CHECK(last.analyzed == 2);
    CHECK(last.failed == 1);
    CHECK(last.skipped == 1);
    CHECK(last.completed == 3);
    CHECK(last.analyzed + last.failed + last.skipped == static_cast<int>(items.size()));
}

TEST_CASE("run_batch reports a failed chart once per copy, under its first copy's name") {
    // D76: a failure list is as long as its count. D51 call 10: the first
    // copy names the chart.
    std::vector<ScanItem> items = items_with_a_copy();
    items[2].title = "a later copy's own name";
    BatchCallbacks callbacks;
    std::atomic<int> runs{0};
    callbacks.analyze = [&runs](const std::string&, const AnalysisSettings&,
                                const std::function<void(float)>&) -> AnalysisResult {
        ++runs;
        throw std::runtime_error("fake analyzer");
    };
    std::vector<std::string> titles;
    callbacks.on_error = [&titles](const std::string& title, const std::string&,
                                   const std::string&) { titles.push_back(title); };
    BatchProgress last;
    callbacks.on_progress = [&last](const BatchProgress& p) { last = p; };

    BatchRun run;
    run.chartmode = "copy-fail-test";
    hydra::store::RecordStore store(":memory:");
    run_batch(items, run, store, /*redo=*/false, 1, callbacks);

    CHECK(runs.load() == 3);
    CHECK(last.failed == 4);
    REQUIRE(titles.size() == 4);
    CHECK(std::count(titles.begin(), titles.end(), items[0].title) == 2);
    CHECK(std::count(titles.begin(), titles.end(), items[2].title) == 0);
}

// Finding 193 (D71, open question 5): a save that fails during a batch used
// to leave run_batch and close Hydra. Now that chart is a failure like any
// other, and the batch goes on.
TEST_CASE("run_batch counts a failed save as a failed chart and goes on") {
    const std::vector<ScanItem> items = fake_items(2);
    const AnalysisResult real = analyze_chart_file(corpus::first_chart_with_notes(), {});
    BatchCallbacks callbacks;
    callbacks.analyze = [&real](const std::string&, const AnalysisSettings&,
                                const std::function<void(float)>&) -> AnalysisResult {
        return real;
    };
    std::vector<std::string> errors;
    callbacks.on_error = [&errors](const std::string& title, const std::string& sentence,
                                   const std::string& error) {
        errors.push_back(title + "|" + sentence + "|" + error);
    };
    BatchProgress last;
    callbacks.on_progress = [&last](const BatchProgress& p) { last = p; };

    const std::string path = testtemp::temp_path("batch_save_fail", ".db");
    std::remove(path.c_str());
    { hydra::store::RecordStore store(path); }
    {  // A trigger refuses chart fake1's result, so its save throws.
        sqlite3* db = nullptr;
        REQUIRE(sqlite3_open(path.c_str(), &db) == SQLITE_OK);
        REQUIRE(sqlite3_exec(db,
                             "CREATE TRIGGER refuse_fake1 BEFORE INSERT ON results"
                             " WHEN NEW.hyhash = 'fake1' BEGIN SELECT RAISE(ABORT, 'boom'); END;",
                             nullptr, nullptr, nullptr) == SQLITE_OK);
        sqlite3_close(db);
    }
    BatchRun run;
    run.chartmode = "save-fail-test";
    {
        hydra::store::RecordStore store(path);
        run_batch(items, run, store, /*redo=*/false, 1, callbacks);

        REQUIRE(errors.size() == 1);
        CHECK(errors[0].rfind("fake 1|Hydra couldn't save to its database (hydra.db). Check that "
                              "the disk isn't full and that no other copy of Hydra is running, "
                              "then try again.|add_row",
                              0) == 0);
        const std::unordered_set<std::string> stored = charts_with_result(store, run, false);
        CHECK(stored.count("fake0") == 1);
        CHECK(stored.count("fake1") == 0);
        CHECK(last.analyzed == 1);
        CHECK(last.failed == 1);
    }
    std::remove(path.c_str());
}

// The batch works the sentence out while the exception's type is known, so
// the screens never read an error's words (D71, ER2 open question 7).
TEST_CASE("run_batch hands on_error the sentence its exception's kind names") {
    BatchCallbacks callbacks;
    callbacks.analyze = [](const std::string&, const AnalysisSettings&,
                           const std::function<void(float)>&) -> AnalysisResult {
        throw hydra::KindedError(hydra::ErrorKind::StoredResult, "x");
    };
    std::vector<std::string> sentences;
    callbacks.on_error = [&sentences](const std::string&, const std::string& sentence,
                                      const std::string&) { sentences.push_back(sentence); };
    BatchRun run;
    run.chartmode = "sentence-test";
    hydra::store::RecordStore store(":memory:");
    run_batch(fake_items(1), run, store, /*redo=*/false, 1, callbacks);

    REQUIRE(sentences.size() == 1);
    CHECK(sentences[0] == "A saved result couldn't be read. Re-analyze this song to replace it.");
}

namespace {

// short_chart_with_long_audio's chart (last note at 100 ms, a 5 s song.ogg)
// with `ini` as its song.ini, as the library scan lists it.
ScanItem scanned_short_chart(const std::string& tag, const std::string& ini) {
    const std::string notes = audiochart::short_chart_with_long_audio(tag);
    audiochart::write_text_file(hydra::parent_folder(notes) + "\\song.ini", ini);
    auto [items, errors] = discover_charts({hydra::parent_folder(notes)});
    REQUIRE(errors.empty());
    REQUIRE(items.size() == 1);
    return items[0];
}

// What run_batch saved for `item` under `run`.
hydra::store::RecordLookup batch_saved(const ScanItem& item, const BatchRun& run) {
    hydra::store::RecordStore store(":memory:");
    run_batch({item}, run, store, /*redo=*/false, 1, {});
    hydra::store::RecordLookup got =
        store.get_record({item.md5, run.chartmode, run.cap_query(), run.lens});
    REQUIRE(got.status == hydra::store::RecordStatus::Ready);
    return got;
}

}  // namespace

TEST_CASE("run_batch saves the song's length from its metadata (D75)") {
    BatchRun run;
    run.chartmode = "length-test";
    const hydra::store::RecordLookup read =
        batch_saved(scanned_short_chart("batch_len", "[song]\nsong_length = 4321\n"), run);
    CHECK(read.song_length_read);
    CHECK(read.song_length_ms == 4321.0);

    // A chart whose metadata cannot be read keeps its length unread: here a
    // .sng that is gone, on a row an older scan wrote.
    const AnalysisResult real = analyze_chart_file(corpus::first_chart_with_notes(), {});
    BatchCallbacks callbacks;
    callbacks.analyze = [&real](const std::string&, const AnalysisSettings&,
                                const std::function<void(float)>&) { return real; };
    ScanItem gone;
    gone.md5 = "gone";
    gone.title = "gone";
    gone.notespath = testtemp::temp_dir("batch_len_gone") + "\\gone.sng";
    hydra::store::RecordStore store(":memory:");
    run_batch({gone}, run, store, /*redo=*/false, 1, callbacks);
    const hydra::store::RecordLookup unread =
        store.get_record({gone.md5, run.chartmode, run.cap_query(), run.lens});
    REQUIRE(unread.status == hydra::store::RecordStatus::Ready);
    CHECK_FALSE(unread.song_length_read);
    CHECK_FALSE(unread.song_length_ms.has_value());
}

TEST_CASE("run_batch's length opens no audio: no audio file, or junk audio, still has one") {
    // D75 item 5. The stated length needs no audio at all.
    BatchRun run;
    run.chartmode = "length-noaudio";
    ScanItem no_audio = scanned_short_chart("batch_len_noaudio", "[song]\nsong_length = 4321\n");
    REQUIRE(DeleteFileW(
        hydra::utf8_to_wide(hydra::parent_folder(no_audio.notespath) + "\\song.ogg").c_str()));
    hydra::store::RecordLookup got = batch_saved(no_audio, run);
    CHECK(got.song_length_read);
    CHECK(got.song_length_ms == 4321.0);

    // No stated length and junk bytes under the audio's name: the last Expert
    // note (100 ms) is the length.
    const ScanItem junk = scanned_short_chart("batch_len_junk", "[song]\nname = Junk\n");
    audiochart::write_text_file(hydra::parent_folder(junk.notespath) + "\\song.ogg",
                                "not audio at all");
    got = batch_saved(junk, run);
    CHECK(got.song_length_read);
    CHECK(got.song_length_ms == 100.0);
}

TEST_CASE("a song.ini delay longer than the stated length saves no length") {
    // The stated length ends before chart time 0, so the owner
    // (app::chart_song_length_ms) gives no length: the song is read, with
    // none.
    BatchRun run;
    run.chartmode = "delay-test";
    const hydra::store::RecordLookup got = batch_saved(
        scanned_short_chart("long_delay", "[song]\nsong_length = 1000\ndelay = 60000\n"), run);
    CHECK(got.song_length_read);
    CHECK_FALSE(got.song_length_ms.has_value());
}

TEST_CASE("discover_charts: a song with no usable name reads (unknown)") {
    namespace fs = std::filesystem;
    const std::string chart = corpus::first_chart_with_suffix(".chart");
    REQUIRE(!chart.empty());

    const fs::path root = hydra::os_path(testtemp::temp_dir("unknown_title"));
    fs::remove_all(root);

    // An empty `name =` line.
    fs::create_directories(root / "empty_name");
    fs::copy_file(fs::u8path(chart), root / "empty_name" / "notes.chart");
    {
        std::ofstream ini(root / "empty_name" / "song.ini", std::ios::binary);
        ini << "[song]\nname =\nartist = Someone\n";
    }
    // No name line at all.
    fs::create_directories(root / "no_name");
    fs::copy_file(fs::u8path(chart), root / "no_name" / "notes.chart");
    {
        std::ofstream ini(root / "no_name" / "song.ini", std::ios::binary);
        ini << "[song]\nartist = Someone\n";
    }
    // A .sng whose embedded name is empty.
    {
        const std::vector<uint8_t> sng =
            testsng::make_sng({{"name", ""}, {"artist", "Someone"}, {"charter", "C"}}, {});
        std::ofstream f(root / "blank.sng", std::ios::binary);
        f.write(reinterpret_cast<const char*>(sng.data()),
                static_cast<std::streamsize>(sng.size()));
    }

    auto [items, errors] = discover_charts({root.u8string()});
    fs::remove_all(root);
    CHECK(errors.empty());
    REQUIRE(items.size() == 3);
    for (const ScanItem& it : items) {
        CAPTURE(it.notespath);
        CHECK(it.title == hydra::kUnknownTitle);
        CHECK(it.artist == "Someone");
    }
}

TEST_CASE("rescan cache: an old placeholder or blank title reads (unknown)") {
    const std::string input = HYDRA_INPUT_DIR;
    auto [items, errors] = discover_charts({input});
    REQUIRE(!items.empty());

    // Library rows written before the fallback existed: a blank title from an
    // empty `name =`, or the old readers' "<unknown title>".
    hydra::store::RecordStore store(":memory:");
    std::vector<hydra::store::ChartLibraryEntry> entries;
    for (size_t i = 0; i < items.size(); ++i) {
        hydra::store::ChartLibraryEntry e = to_library_entry(items[i]);
        e.title = i % 2 ? "<unknown title>" : "";
        entries.push_back(std::move(e));
    }
    store.rebuild_chart_library(entries);
    hydra::store::ChartLibraryCache cache = store.chart_library_cache();

    auto [items2, errors2] = discover_charts({input}, ScanCallbacks{}, &cache);
    REQUIRE(items2.size() == items.size());
    for (const ScanItem& it : items2) CHECK(it.title == hydra::kUnknownTitle);
}

namespace {

// This process's scratch folder for one scan fixture (testtemp::temp_dir).
std::string scan_fixture_dir(const char* name) {
    return testtemp::temp_dir(std::string("scan_case_") + name);
}

using testtemp::write_bytes;

}  // namespace

TEST_CASE("discover_charts finds a folder whose notes and ini names are capitalized") {
    const std::string dir = scan_fixture_dir("caps");
    write_bytes(dir + "\\Notes.mid",
                  testmidi::smf(testmidi::concat({testmidi::track_name("PART DRUMS"),
                                                  testmidi::set_tempo(),
                                                  testmidi::note_on(96, 100),
                                                  testmidi::end_of_track()})));
    const std::string ini = "[song]\r\nname = Capital Case\r\nartist = Someone\r\n"
                            "charter = Someone Else\r\n";
    write_bytes(dir + "\\Song.ini", std::vector<uint8_t>(ini.begin(), ini.end()));

    auto [items, errors] = discover_charts({dir});
    REQUIRE(errors.empty());
    REQUIRE(items.size() == 1);
    CHECK(items[0].title == "Capital Case");
    CHECK(items[0].notespath == dir + "\\Notes.mid");
}
