import sqlite3, os, collections
db = r"C:\Users\Patrick\AppData\Local\Temp\claude\C--Users-Patrick-Downloads-Hydra-hydra-test\3dbe8199-05ae-4b84-8477-f6bbc98854d5\scratchpad\db\hydra.db"
c = sqlite3.connect("file:" + db + "?mode=ro", uri=True)
q = lambda s, *a: c.execute(s, a).fetchall()
print("file bytes", os.path.getsize(db))
print("page_size", q("PRAGMA page_size"), "page_count", q("PRAGMA page_count"), "freelist", q("PRAGMA freelist_count"))
print("tables/indexes:", q("SELECT type,name,tbl_name FROM sqlite_master ORDER BY tbl_name,type"))
# dbstat if available
try:
    print("dbstat:", q("SELECT name, SUM(pgsize) FROM dbstat GROUP BY name ORDER BY 2 DESC"))
except Exception as e:
    print("dbstat unavailable:", e)
print("--- counts")
for t in ["songmeta","charts","dynamics","meta","results","paths","path_refs"]:
    print(t, q(f"SELECT COUNT(*) FROM {t}"))
print("meta rows:", q("SELECT key, value FROM meta"))
print("--- songmeta sizes")
print(q("SELECT SUM(length(hyhash)), SUM(length(ref_name)), SUM(length(ref_artist)), SUM(length(ref_charter)), SUM(length(tempomap)), COUNT(length_ms), SUM(length_version=2), SUM(length_version=0), SUM(length_version NOT IN (0,2)) FROM songmeta"))
print("songmeta with no results row:", q("SELECT COUNT(*) FROM songmeta s WHERE NOT EXISTS (SELECT 1 FROM results r WHERE r.hyhash=s.hyhash)"))
print("songmeta not in charts:", q("SELECT COUNT(*) FROM songmeta s WHERE NOT EXISTS (SELECT 1 FROM charts ch WHERE ch.md5=s.hyhash)"))
print("results not in charts:", q("SELECT COUNT(*) FROM results r WHERE NOT EXISTS (SELECT 1 FROM charts ch WHERE ch.md5=r.hyhash)"))
print("results not in charts, by version:", q("SELECT hyversion, COUNT(*) FROM results r WHERE NOT EXISTS (SELECT 1 FROM charts ch WHERE ch.md5=r.hyhash) GROUP BY hyversion"))
print("dynamics not in charts:", q("SELECT COUNT(*) FROM dynamics d WHERE NOT EXISTS (SELECT 1 FROM charts ch WHERE ch.md5=d.md5)"))
print("hyhash sample lengths:", q("SELECT length(hyhash), COUNT(*) FROM songmeta GROUP BY 1"))
print("--- results by version/lens")
print(q("SELECT hyversion, chartmode, sp_cap, ms_enabled, ms_value, depth_mode, depth_value, legacy_fills, hex(rules_fp), COUNT(*) FROM results GROUP BY 1,2,3,4,5,6,7,8,9 ORDER BY 10 DESC"))
print("results per (hyhash,chartmode):", q("SELECT n, COUNT(*) FROM (SELECT hyhash, chartmode, COUNT(*) n FROM results GROUP BY 1,2) GROUP BY n"))
print("results per hyhash (any mode):", q("SELECT n, COUNT(*) FROM (SELECT hyhash, COUNT(*) n FROM results GROUP BY 1) GROUP BY n"))
print("--- paths sharing")
print("distinct phash:", q("SELECT COUNT(*) FROM paths"))
print("refs per node:", q("SELECT n, COUNT(*) FROM (SELECT hyhash, chartmode, phash, COUNT(*) n FROM path_refs GROUP BY 1,2,3) GROUP BY n"))
print("nodes with no ref (orphans):", q("SELECT COUNT(*) FROM paths p WHERE NOT EXISTS (SELECT 1 FROM path_refs r WHERE r.hyhash=p.hyhash AND r.chartmode=p.chartmode AND r.phash=p.phash)"))
print("refs with no node:", q("SELECT COUNT(*) FROM path_refs r WHERE NOT EXISTS (SELECT 1 FROM paths p WHERE r.hyhash=p.hyhash AND r.chartmode=p.chartmode AND r.phash=p.phash)"))
print("refs whose result is gone:", q("SELECT COUNT(*) FROM path_refs r WHERE NOT EXISTS (SELECT 1 FROM results x WHERE x.result_id=r.result_id)"))
print("phash length:", q("SELECT length(phash), COUNT(*) FROM paths GROUP BY 1"))
print("paths bytes: hyhash,chartmode,phash,payload", q("SELECT SUM(length(hyhash)), SUM(length(chartmode)), SUM(length(phash)), SUM(length(payload)), AVG(length(payload)), MAX(length(payload)) FROM paths"))
print("path_refs bytes: hyhash,chartmode,phash", q("SELECT SUM(length(hyhash)), SUM(length(chartmode)), SUM(length(phash)) FROM path_refs"))
print("payload identical across charts (same bytes, different chart):", q("SELECT COUNT(*) FROM (SELECT payload FROM paths GROUP BY payload HAVING COUNT(*)>1)"))
print("results structure bytes:", q("SELECT SUM(length(structure)), AVG(length(structure)), MAX(length(structure)), SUM(length(bestpath)), SUM(length(rules_fp)) FROM results"))
print("nodes per result:", q("SELECT MIN(n), AVG(n), MAX(n) FROM (SELECT result_id, COUNT(*) n FROM path_refs GROUP BY 1)"))
